### ISSUE TITLE
Allow multiple filters?

### ISSUE THREAD

**Issue by jamie9090** [wesmoncrief/obsidian-todoist-text#13]
This is exactly what I need, but would love to have multiple filters.

I'm basically trying to get different ideas from Todoist into Obsidian as text.

**Comment by wesmoncrief** [comment]
Thanks for filing! I'm planning to implement it today!

I'm thinking of doing this by allowing users to have multiple keywords configured. E.g., you could have a keyword called `@@TODOIST_WORK_FILTER@@` and another called `@@TODOIST_PERSONAL_FILTER@@`, each with its own query definition.

Does this sound like what you'd want?

**Comment by jamie9090** [comment]
Perfect!

**Comment by wesmoncrief** [comment]
Done! Once you update your plugin, it should be working. Let me know if there's any problems!
