### ISSUE TITLE
Retrieve Todoist task description?

### ISSUE THREAD

**Issue by jamie9090** [wesmoncrief/obsidian-todoist-text#14]
Would love to be able to retrieve the Todoist task description

**Comment by wesmoncrief** [comment]
Thanks for filing! Totally great suggestion. This probably fits in with https://github.com/wesmoncrief/obsidian-todoist-text/issues/5 and https://github.com/wesmoncrief/obsidian-todoist-text/issues/7 - so I'd probably combine this with some kind of settings UI to allow you to choose which pieces of information are displayed.

My first thought here is that we'd want the render to look something like this:
```
- [ ] my task ...
    - here's the description
    - [ ] here is some subtask of it ...
        - here's the subtask description
```

Does that seem like the kind of thing you're looking for?

**Comment by jamie9090** [comment]
Fantastic!

**Comment by jamie9090** [comment]
IF possible, I would also request the ability to COMPLETE task in Todoist once added to Obsidian via filter. 

This is really powerful for a use case where alot of Todoist just becomes a "quick capture" front-end for Obsidian.

**Comment by wesmoncrief** [comment]
Cool! I've filed https://github.com/wesmoncrief/obsidian-todoist-text/issues/17 which can be used for further discussion about the syncing feature. Please let me know what you think in that issue!

**Comment by wesmoncrief** [comment]
Done! Just upgrade and you should get the changes!

 I only added support for descriptions here, and it's always enabled.

I'll follow up sometime later with #5 , which should allow pulling a couple extra fields and allow for more customization in rendering
