### ISSUE TITLE
Command fetching tasks not working

### ISSUE THREAD

**Issue by guihasparyk** [wesmoncrief/obsidian-todoist-text#22]
I can't use the plugin anymore. It was working fine a few days ago...

It happens the folowing:

- ![image](https://user-images.githubusercontent.com/50344202/205965972-8ebba632-d5e6-420c-be7b-7bccefc802ec.png)
or...
- ![image](https://user-images.githubusercontent.com/50344202/205966562-12d0b6c3-989c-47e3-9769-4379fa8511fb.png)

I would be glad if someone could help me with this.

**Comment by wesmoncrief** [comment]
Thanks @guihasparyk for filing, and thanks @madajczyk for fixing! The fix should be released now, please update your plugin and let me know if there's any more issues.
