### ISSUE TITLE
Priority number is inverted

### ISSUE THREAD

**Issue by oneross** [wesmoncrief/obsidian-todoist-text#25]
The priority tags (p1...p4) are inverted from how they're displayed in the Todoist API.  For example, in this view (my "Most Important Things" filter), I have 5 P1 (red) tasks and 1 P2 (orange) task, but in the Todoist Text plugin output I have 5 P4 tasks and 1 P3 task.

![Example of inverted priority output](https://github.com/oneross/assets/raw/main/img/2023-01-03-todoist-text-inverted-priority.png)

---

I noted in using the Todoist API in a python person dashboard project that the priority value in the schema goes from 1 (lowest priority) to 4 (highest priority), quite the inverse of the way it's represented in the Todoist UI, and created a (naively engineered with no exception handling) helper function to fix the display logic:

![Example of naive Todoist priority inversion logic](https://github.com/oneross/assets/raw/main/img/2023-01-03-example-invert-priority-function.png)

---

I've spent zero time looking at the codebase and am a complete javascript noob, but searching for priority only reveals one instance outside of the Readme.  I'm thinking maybe some wrapper / helper functionality in this area would do the trick?

https://github.com/wesmoncrief/obsidian-todoist-text/blob/9075241206436d5c930e7872582158447f625a6d/src/updateFileFromServer.ts#L102-L108

However, given that people may have already built workflow around the inverted logic, it may be better to make this an optional, non-default change; surfacing that configuration option is completely beyond me at present.

---

I'd love to try to gin up a change and submit a PR, but given my lack of fluency in js, having never created an Obsidian plugin and so not having a good testing workflow, and my other priorities I can't promise it'll be anytime soon.

Have a great day, and thanks for the awesome plugin!  It's a vital part of my workflow.

**Comment by wesmoncrief** [comment]
Thanks for filing! This was actually noticed a few days ago - https://github.com/wesmoncrief/obsidian-todoist-text/pull/24

@madajczyk has a fix in progress on that PR, so hopefully this should be resolved soon!

**Comment by wesmoncrief** [comment]
This should be fixed with the 1.4.0 which I just released, thanks to @madajczyk . Let me know if it's not working as expected!
