### ISSUE TITLE
Breaks with Obsidian 1.3.5 Update

### ISSUE THREAD

**Issue by skullbunnygalaxy** [wesmoncrief/obsidian-todoist-text#31]
I updated Obsidian to 1.3.5, which was released today.

Both manual and automated replacement of keywords with Todoist tasks stopped working.

I have tried restarting Obsidian, turning the plugin off and on again, and testing with simpler queries.

**Comment by skullbunnygalaxy** [comment]
Closing as I finally got it to start working again after a full restart of my computer.

**Comment by wesmoncrief** [comment]
awesome, thanks
