### ISSUE TITLE
Pulling tasks from archived projects

### ISSUE THREAD

**Issue by aventuraviper** [wesmoncrief/obsidian-todoist-text#8]
I have just realised that the plugin is somehow pickiong up tasks that are in archived projects. I.e. a filter like overdue|today doesn't appear the same between todoist and what the plugin produces

**Comment by wesmoncrief** [comment]
Hey, thanks again for filing!

Hmm, I'm having a hard time reproducing. I tried creating a new project with one task in it that's due today. Then, I archived the project. Then, I ran the plugin with the query "today|overdue". The task did _not_ show up in obsidian.

Mind showing me how to reproduce?

**Comment by aventuraviper** [comment]
So it appears that there's something odd occuring with Todoist that is likely causing this. It turns out it was only archived projects with the GCal 2-way sync on (apparently the 2-way sync continues to populate the archived project, but not visibly in Todoist).

I'd say this is a bug with Todoist rather than the plugin
